version: "3.1"
services:
   agenda_solidaria-db:
    image: postgres:14.1
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agenda_solidaria
    restart: always
    volumes:
      - ./src/main/database:/docker-entrypoint-initdb.d
